// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../src/components/atoms/DividerText/DividerText.stories');
  require('../src/components/atoms/Icons/Icons.stories');
  require('../src/components/atoms/Shimmer/Shimmer.stories');
  require('../src/components/molecules/ClassCard/ClassCard.stories');
  require('../src/components/molecules/ClassDetails/ClassDetails.stories');
  require('../src/components/molecules/DoubleButtonPopup/DoubleButtonPopup.stories');
  require('../src/components/molecules/NoAttendancePopup/NoAttendancePopup.stories');
  require('../src/components/molecules/OauthProvider/OauthProvider.stories');
  require('../src/components/molecules/SelectTimeEditPopup/SelectTimeEditPopup.stories');
  require('../src/components/molecules/SingleButtonPopup/SingleButtonPopup.stories');
  require('../src/components/molecules/SpinnerLoader/SpinnerLoader.stories');
  require('../src/components/molecules/StudentListItem/StudentListItem.stories');
  require('../src/components/molecules/StudentPresentListItem/StudentPresentListItem.stories');
  require('../src/components/molecules/UserInfo/UserInfo.stories');
  require('../src/components/molecules/UserPresentEditPopup/UserPresentEditPopup.stories');
  require('../src/components/molecules/UserPresentPopup/UserPresentPopup.stories');
  require('../src/components/organisms/AppIntro/ChooseRole/ChooseRole.stories');
  require('../src/components/organisms/AppIntro/ForgotPassword/ForgotPassword.stories');
  require('../src/components/organisms/AppIntro/Loading/Loading.stories');
  require('../src/components/organisms/AppIntro/SignIn/SignIn.stories');
  require('../src/components/organisms/AppIntro/SignUp/SignUp.stories');
  require('../src/components/organisms/Common/ChangePassword/ChangePassword.stories');
  require('../src/components/organisms/Common/ConnectionLost/ConnectionLost.stories');
  require('../src/components/organisms/Common/DrawerContent/DrawerContent.stories');
  require('../src/components/organisms/Common/EmptyClass/EmptyClass.stories');
  require('../src/components/organisms/Common/MyAccount/MyAccount.stories');
  require('../src/components/organisms/Student/AttendanceRecord/AttendanceRecord.stories');
  require('../src/components/organisms/Student/GiveResponse/GiveResponse.stories');
  require('../src/components/organisms/Student/JoinClassFinal/JoinClassFinal.stories');
  require('../src/components/organisms/Student/JoinClassForm/JoinClassForm.stories');
  require('../src/components/organisms/Student/StudentClassList/StudentClassList.stories');
  require('../src/components/organisms/Student/SuccessResponse/SuccessResponse.stories');
  require('../src/components/organisms/Student/TurnOnWifi/TurnOnWifi.stories');
  require('../src/components/organisms/Student/UnsuccessfulResponse/UnsuccessfulResponse.stories');
  require('../src/components/organisms/Teacher/AttendanceRecordStudentList/AttendanceRecordStudentList.stories');
  require('../src/components/organisms/Teacher/AttendanceSessionRecord/AttendanceSessionRecord.stories');
  require('../src/components/organisms/Teacher/ClassSettings/ClassSettings.stories');
  require('../src/components/organisms/Teacher/CreateClass/CreateClass.stories');
  require('../src/components/organisms/Teacher/CurrentAttendanceSession/CurrentAttendanceSession.stories');
  require('../src/components/organisms/Teacher/EditAttendanceSession/EditAttendanceSession.stories');
  require('../src/components/organisms/Teacher/EditStudentAttendanceRecord/EditStudentAttendanceRecord.stories');
  require('../src/components/organisms/Teacher/InviteStudent/InviteStudent.stories');
  require('../src/components/organisms/Teacher/StartAttendanceSession/StartAttendanceSession.stories');
  require('../src/components/organisms/Teacher/StudentList/StudentList.stories');
  require('../src/components/organisms/Teacher/StudentsEmptyList/StudentsEmptyList.stories');
  require('../src/components/organisms/Teacher/TeacherClassList/TeacherClassList.stories');
}

const stories = [
  '../src/components/atoms/DividerText/DividerText.stories',
  '../src/components/atoms/Icons/Icons.stories',
  '../src/components/atoms/Shimmer/Shimmer.stories',
  '../src/components/molecules/ClassCard/ClassCard.stories',
  '../src/components/molecules/ClassDetails/ClassDetails.stories',
  '../src/components/molecules/DoubleButtonPopup/DoubleButtonPopup.stories',
  '../src/components/molecules/NoAttendancePopup/NoAttendancePopup.stories',
  '../src/components/molecules/OauthProvider/OauthProvider.stories',
  '../src/components/molecules/SelectTimeEditPopup/SelectTimeEditPopup.stories',
  '../src/components/molecules/SingleButtonPopup/SingleButtonPopup.stories',
  '../src/components/molecules/SpinnerLoader/SpinnerLoader.stories',
  '../src/components/molecules/StudentListItem/StudentListItem.stories',
  '../src/components/molecules/StudentPresentListItem/StudentPresentListItem.stories',
  '../src/components/molecules/UserInfo/UserInfo.stories',
  '../src/components/molecules/UserPresentEditPopup/UserPresentEditPopup.stories',
  '../src/components/molecules/UserPresentPopup/UserPresentPopup.stories',
  '../src/components/organisms/AppIntro/ChooseRole/ChooseRole.stories',
  '../src/components/organisms/AppIntro/ForgotPassword/ForgotPassword.stories',
  '../src/components/organisms/AppIntro/Loading/Loading.stories',
  '../src/components/organisms/AppIntro/SignIn/SignIn.stories',
  '../src/components/organisms/AppIntro/SignUp/SignUp.stories',
  '../src/components/organisms/Common/ChangePassword/ChangePassword.stories',
  '../src/components/organisms/Common/ConnectionLost/ConnectionLost.stories',
  '../src/components/organisms/Common/DrawerContent/DrawerContent.stories',
  '../src/components/organisms/Common/EmptyClass/EmptyClass.stories',
  '../src/components/organisms/Common/MyAccount/MyAccount.stories',
  '../src/components/organisms/Student/AttendanceRecord/AttendanceRecord.stories',
  '../src/components/organisms/Student/GiveResponse/GiveResponse.stories',
  '../src/components/organisms/Student/JoinClassFinal/JoinClassFinal.stories',
  '../src/components/organisms/Student/JoinClassForm/JoinClassForm.stories',
  '../src/components/organisms/Student/StudentClassList/StudentClassList.stories',
  '../src/components/organisms/Student/SuccessResponse/SuccessResponse.stories',
  '../src/components/organisms/Student/TurnOnWifi/TurnOnWifi.stories',
  '../src/components/organisms/Student/UnsuccessfulResponse/UnsuccessfulResponse.stories',
  '../src/components/organisms/Teacher/AttendanceRecordStudentList/AttendanceRecordStudentList.stories',
  '../src/components/organisms/Teacher/AttendanceSessionRecord/AttendanceSessionRecord.stories',
  '../src/components/organisms/Teacher/ClassSettings/ClassSettings.stories',
  '../src/components/organisms/Teacher/CreateClass/CreateClass.stories',
  '../src/components/organisms/Teacher/CurrentAttendanceSession/CurrentAttendanceSession.stories',
  '../src/components/organisms/Teacher/EditAttendanceSession/EditAttendanceSession.stories',
  '../src/components/organisms/Teacher/EditStudentAttendanceRecord/EditStudentAttendanceRecord.stories',
  '../src/components/organisms/Teacher/InviteStudent/InviteStudent.stories',
  '../src/components/organisms/Teacher/StartAttendanceSession/StartAttendanceSession.stories',
  '../src/components/organisms/Teacher/StudentList/StudentList.stories',
  '../src/components/organisms/Teacher/StudentsEmptyList/StudentsEmptyList.stories',
  '../src/components/organisms/Teacher/TeacherClassList/TeacherClassList.stories',
];

module.exports = {
  loadStories,
  stories,
};
